---
kind: pipeline
type: docker
name: default

steps:
  - name: ch1
    image: golang:1.15
    commands:
      - cd ch1
      - go run main.go
      - cd hello
      - go test
  - name: ch2
    image: golang:1.15
    commands:
      - cd ch2/handle
      - go test
  - name: ch3
    image: golang:1.15
    commands:
      - cd ch3/copy
      - go test
      - cd ../random
      - go run main.go sample.dat 1024
      - cd random
      - go test
